language: go

go:
  - 1.4
  - 1.5
  - tip

install:
  - go get -u golang.org/x/tools/cmd/goimports

script:
  - go test ./...
  - >
    goimports -d -e ./ | grep '.*' && { echo; echo "Aborting due to non-empty goimports output."; exit 1; } || :
